version: "3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_HOSTNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload  
    ## reload option is very useful for dev because it automatically reloads the container when any revision occurs during environment
    env_file:
      - ./.env
    volumes: 
      - .:/app:ro
    ## this is to sync the current dirctory on our local machine with /app in the container
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
        