version: "3"

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${DATABASE_HOSTNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  api:
    environment:
      DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    build: .
    command: pytest  
    # env_file:
    #   - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
        